title: Mindstream today
email: ask@mindstraem.today
description: The blog is about homemade R&D in computer science for enthusiasts.
baseurl: ""
url: "mindstraem.today"
github_username:  mindstream-today

languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
